### PR TITLE
I7: exclude classes by configuration

### PR DESCRIPTION
**Pull request by volkerkochnovatec**
This change is [Reviewable](https://reviewable.io/reviews/novatecconsulting/stereotype-check/14)

### CODE REVIEW

**Comment by ruben-burr** [comment]
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

_[stereotype.check.plugin.test/src/test/java/info/novatec/architecture/check/StereotypeCheckTest.java, line 486 at r1](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/14#-KU1Dan8B2DWdSwl4jak:-KU1Dan9STLKqSXcv-wQ:b37mzm) ([raw file](https://github.com/novatecconsulting/stereotype-check/blob/f6f57c9e0083565a3b9dd70253c71d22f6bb2d64/stereotype.check.plugin.test/src/test/java/info/novatec/architecture/check/StereotypeCheckTest.java#L486)):_

> ``` Java
> 
>   /**
>    * Ignore all classes that ends to Test.
> ```

end statt ends

---

_[stereotype.check.plugin.test/src/test/java/info/novatec/architecture/check/StereotypeCheckTest.java, line 492 at r1](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/14#-KU1EZk7GbO0YIzqYCwE:-KU1EZk7GbO0YIzqYCwF:bvt0c93) ([raw file](https://github.com/novatecconsulting/stereotype-check/blob/f6f57c9e0083565a3b9dd70253c71d22f6bb2d64/stereotype.check.plugin.test/src/test/java/info/novatec/architecture/check/StereotypeCheckTest.java#L492)):_

> ``` Java
>    */
>   @Test
>   public void testTestClassExcluded() throws Exception {
> ```

Benennung Testmethoden bitte umdrehen

---

_[stereotype.check.plugin.test/src/test/resources/stereotypeWithExcludedClass.xml, line 1 at r1](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/14#-KU1EQRPM0AEW_IT1SaA:-KU1EQRQqbqrSze_jhwM:b-3wfy7o) ([raw file](https://github.com/novatecconsulting/stereotype-check/blob/f6f57c9e0083565a3b9dd70253c71d22f6bb2d64/stereotype.check.plugin.test/src/test/resources/stereotypeWithExcludedClass.xml#L1)):_

> ``` XML
> <?xml version="1.0" encoding="UTF-8"?>
> ```

Bitte Config Dateien entsprechend umbenennen. (withoutExcludedClasses)

---

_[stereotype.check.plugin.test/src/test/resources/stereotypeWithExcludedClass.xml, line 17 at r1](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/14#-KU1Eo3N2KN9SubBroY0:-KU1Eo3N2KN9SubBroY1:b-7er70o) ([raw file](https://github.com/novatecconsulting/stereotype-check/blob/f6f57c9e0083565a3b9dd70253c71d22f6bb2d64/stereotype.check.plugin.test/src/test/resources/stereotypeWithExcludedClass.xml#L17)):_

> ``` XML
>     limitations under the License.
>  -->
> ```

Hier wäre ein Kommentar hilfreich, was denn jetzt das spezielle ist an der Datei. Ist sonst schwer herauszufinden. Vielleicht kannst du sie auch reduzieren.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/14)_

**Comment by volkerkochnovatec** [comment]
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

_[stereotype.check.plugin.test/src/test/java/info/novatec/architecture/check/StereotypeCheckTest.java, line 486 at r1](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/14#-KU1Dan8B2DWdSwl4jak:-KV98zQU-vnV6ERN7xTD:b-896fix) ([raw file](https://github.com/novatecconsulting/stereotype-check/blob/f6f57c9e0083565a3b9dd70253c71d22f6bb2d64/stereotype.check.plugin.test/src/test/java/info/novatec/architecture/check/StereotypeCheckTest.java#L486)):_
<details><summary>

<i>Previously, ruben-burr (Ruben Burr) wrote…</i></summary>



> end statt ends
> </details>
> Done.

---

_[stereotype.check.plugin.test/src/test/java/info/novatec/architecture/check/StereotypeCheckTest.java, line 492 at r1](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/14#-KU1EZk7GbO0YIzqYCwE:-KV99-JTn3KD7ImfNrWo:b-896fix) ([raw file](https://github.com/novatecconsulting/stereotype-check/blob/f6f57c9e0083565a3b9dd70253c71d22f6bb2d64/stereotype.check.plugin.test/src/test/java/info/novatec/architecture/check/StereotypeCheckTest.java#L492)):_
<details><summary>

<i>Previously, ruben-burr (Ruben Burr) wrote…</i></summary>



> Benennung Testmethoden bitte umdrehen
> </details>
> Done.

---

_[stereotype.check.plugin.test/src/test/resources/stereotypeWithExcludedClass.xml, line 1 at r1](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/14#-KU1EQRPM0AEW_IT1SaA:-KV990NTzMs0AKBv2I9r:b-896fix) ([raw file](https://github.com/novatecconsulting/stereotype-check/blob/f6f57c9e0083565a3b9dd70253c71d22f6bb2d64/stereotype.check.plugin.test/src/test/resources/stereotypeWithExcludedClass.xml#L1)):_
<details><summary>

<i>Previously, ruben-burr (Ruben Burr) wrote…</i></summary>



> Bitte Config Dateien entsprechend umbenennen. (withoutExcludedClasses)
> </details>
> Done.

---

_[stereotype.check.plugin.test/src/test/resources/stereotypeWithExcludedClass.xml, line 17 at r1](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/14#-KU1Eo3N2KN9SubBroY0:-KV990gtgh-Q1MslVOW7:b-896fix) ([raw file](https://github.com/novatecconsulting/stereotype-check/blob/f6f57c9e0083565a3b9dd70253c71d22f6bb2d64/stereotype.check.plugin.test/src/test/resources/stereotypeWithExcludedClass.xml#L17)):_
<details><summary>

<i>Previously, ruben-burr (Ruben Burr) wrote…</i></summary>



> Hier wäre ein Kommentar hilfreich, was denn jetzt das spezielle ist an der Datei. Ist sonst schwer herauszufinden. Vielleicht kannst du sie auch reduzieren.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/14)_

**Comment by ruben-burr** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

_[stereotype.check.plugin.test/src/test/resources/stereotypeWithoutExcludedClass.xml, line 19 at r2](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/14#-KWHoiUslnH8F6qOipsh:-KWHoiUslnH8F6qOipsi:b-bzp7av) ([raw file](https://github.com/novatecconsulting/stereotype-check/blob/ae09faeb9a980e413f57e30a2093a1012a6fcd05/stereotype.check.plugin.test/src/test/resources/stereotypeWithoutExcludedClass.xml#L19)):_

> ``` XML
>

**Comment by volkerkochnovatec** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

_[stereotype.check.plugin.test/src/test/resources/stereotypeWithoutExcludedClass.xml, line 19 at r2](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/14#-KWHoiUslnH8F6qOipsh:-KWHrqFZRVLjzxd7WyHE:b-896fix) ([raw file](https://github.com/novatecconsulting/stereotype-check/blob/ae09faeb9a980e413f57e30a2093a1012a6fcd05/stereotype.check.plugin.test/src/test/resources/stereotypeWithoutExcludedClass.xml#L19)):_
<details><summary>

<i>Previously, ruben-burr (Ruben Burr) wrote…</i></summary>



> What does this sentence mean? If ignoring is the default, then the excludedclasses tag would not be necessary. 
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/14)_

**Pull request merged**
