### PR TITLE
Classes that are not in an application package, are ignored (#I46)

### PR DESCRIPTION
**Pull request by volkerkochnovatec**
This change is [Reviewable](https://reviewable.io/reviews/novatecconsulting/stereotype-check/50)

### CODE REVIEW

**Comment by simon-weimann** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[stereotype.check.plugin/src/main/java/info/novatec/ita/check/ClassInfo.java, line 410 at r1](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/50#-Kdje63JEBmngFicFeOb:-Kdje63JEBmngFicFeOc:bimp9ee) ([raw file](https://github.com/novatecconsulting/stereotype-check/blob/9dd64712edab72cc214b5d01fce6dcc2b0ea5c13/stereotype.check.plugin/src/main/java/info/novatec/ita/check/ClassInfo.java#L410)):*
> +"."+
I don't get why you are using defaultString()

In case packageName is null (class has no package?) then the full class name would start with a dot which is not right 

if we want to support the case for class checking without a package definition, I think it would be worth creating a test for this. I expect other errors as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/50)*

**Comment by simon-weimann** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/50)*

**Comment by volkerkochnovatec** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[stereotype.check.plugin/src/main/java/info/novatec/ita/check/ClassInfo.java, line 410 at r1](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/50#-Kdje63JEBmngFicFeOb:-Kdju9JukcE3DUwjt8WW:b-i7k0c5) ([raw file](https://github.com/novatecconsulting/stereotype-check/blob/9dd64712edab72cc214b5d01fce6dcc2b0ea5c13/stereotype.check.plugin/src/main/java/info/novatec/ita/check/ClassInfo.java#L410)):*
<details><summary><i>Previously, simon-weimann (Simon Weimann) wrote…</i></summary><blockquote>

> +"."+
I don't get why you are using defaultString()

In case packageName is null (class has no package?) then the full class name would start with a dot which is not right 

if we want to support the case for class checking without a package definition, I think it would be worth creating a test for this. I expect other errors as well
</blockquote></details>

Fehler behoben und Test gebaut

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/50)*

**Comment by simon-weimann** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/50#-:-Kdk7CY29S2YNkbk2sGr:bnfp4nl)*

**Pull request merged**
