### PR TITLE
#8: changed to maven wrapper

### PR DESCRIPTION
**Pull request by ruben-burr**
This change is [Reviewable](https://reviewable.io/reviews/novatecconsulting/stereotype-check/11)

### CODE REVIEW

**Comment by ruben-burr** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[a discussion](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/11#-KSuCWvxPlZJj3DQeBrw:-KSuCWvy9gbG2txYLPto:b-i7gw0s) (no related file):_
die jar datei fehlt, deshalb tut der build im travis nicht.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/11)_

**Comment by ruben-burr** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

_[a discussion](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/11#-KSuCWvxPlZJj3DQeBrw:-KSuH94VceGDdRHlBzIG:bt4ug6i) (no related file):_
<details><summary>

<i>Previously, ruben-burr (Ruben Burr) wrote…</i></summary>



> die jar datei fehlt, deshalb tut der build im travis nicht.
> </details>
> wurde hinzugefügt und tut jetzt

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/11)_

**Comment by simon-weimann** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/11)_

**Comment by simon-weimann** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[a discussion](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/11#-KSuCWvxPlZJj3DQeBrw:-KSuqKdqMFuv8RJAFhKd:b32wtd) (no related file):_
<details><summary>

<i>Previously, ruben-burr (Ruben Burr) wrote…</i></summary>



> wurde hinzugefügt und tut jetzt
> </details>
> ok

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/11)_

**Pull request merged**
