### PR TITLE
upload eclipse plugin (#9)

### PR DESCRIPTION
**Pull request by volkerkochnovatec**
This change is [Reviewable](https://reviewable.io/reviews/novatecconsulting/stereotype-check/30)

### CODE REVIEW

**Comment by simon-weimann** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[stereotype.check.repository/pom.xml, line 3 at r1](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/30#-KZVYYgNafgs5QV5-5IO:-KZVYYgNafgs5QV5-5IP:b-clac35) ([raw file](https://github.com/novatecconsulting/stereotype-check/blob/f2d1926eeadcda6a13d03797e4c63ad773581c14/stereotype.check.repository/pom.xml#L3)):*
> ```XML
> <?xml version="1.0"?>
>

**Comment by simon-weimann** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[stereotype.check.repository/category.xml, line 9 at r1](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/30#-KZVcNaax3TA5CH0NuJJ:-KZVcNaax3TA5CH0NuJK:b-ve20bq) ([raw file](https://github.com/novatecconsulting/stereotype-check/blob/f2d1926eeadcda6a13d03797e4c63ad773581c14/stereotype.check.repository/category.xml#L9)):*
> ```XML
>     You may obtain a copy of the License at
>    
>         http://www.apache.org/licenses/LICENSE-2.0
> ```

hier hat es glaube auch einen unnötigen change 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/30)*

**Comment by volkerkochnovatec** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[stereotype.check.repository/category.xml, line 9 at r1](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/30#-KZVcNaax3TA5CH0NuJJ:-KZVesnG98fo_9MN94Rd:b-896fix) ([raw file](https://github.com/novatecconsulting/stereotype-check/blob/f2d1926eeadcda6a13d03797e4c63ad773581c14/stereotype.check.repository/category.xml#L9)):*
<details><summary><i>Previously, simon-weimann (Simon Weimann) wrote…</i></summary><blockquote>

hier hat es glaube auch einen unnötigen change 
</blockquote></details>

Done.

---

*[stereotype.check.repository/pom.xml, line 3 at r1](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/30#-KZVYYgNafgs5QV5-5IO:-KZVfXsnmY2NBsV_Pk8L:b-896fix) ([raw file](https://github.com/novatecconsulting/stereotype-check/blob/f2d1926eeadcda6a13d03797e4c63ad773581c14/stereotype.check.repository/pom.xml#L3)):*
<details><summary><i>Previously, simon-weimann (Simon Weimann) wrote…</i></summary><blockquote>

hier hat es die formatierung zerhauen
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/30)*

**Comment by simon-weimann** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/novatecconsulting/stereotype-check/30)*

**Pull request merged**
